name: xxo
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_console: ^1.0.0
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  mockito: ^5.0.10
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
